os:
    - linux

language: c

before_install:
    - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get update -qq; fi
    - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get install -qq libkrb5-3 libkrb5-dev libgssapi-krb5-2 krb5-config krb5-doc krb5-locales krb5-multidev krb5-gss-samples
    - mkdir ci-build
    - ./autogen.sh

install:
    - cd ci-build
    - ../configure --srcdir=`dirname "$PWD"` --enable-maintainer-mode $COVERAGE
    - ulimit -c unlimited; make -j3

after_failure:
    - find . -name test-suite.log -print0 | xargs -0 cat
    - if [ $TRAVIS_OS_NAME = linux ]; then echo "thread apply all bt" > x; find . -name core.\* -print | while read gdb; do gdb -batch -x x `file "$core"|sed -e "s/^[^']*'//" -e "s/[ '].*$//"` "$core"; done; fi

compiler:
    - clang
    - gcc

notifications:
    email:
	- lukeh@padl.com

